### ISSUE TITLE
Integration with builder library?

### ISSUE THREAD

**Issue by chessai** [byteverse/bytelog#1]
The bounded builder type would be pretty awesome with this

**Comment by andrewthad** [comment]
In e5d3b8f946c1f4f9f8a19fd7dc11152a896fa73d, I've added a `byteArray` function. The function for integrating with the `builder` library would look like:

    builder :: Logger -> Builder -> IO ()
    builder g = Logger.byteArray g . Builder.build

I'm not inclined to pick up a dependency just to provide a function this simple though.

**Comment by chessai** [comment]
I was talking about bounded builder, which you already depend on

**Comment by andrewthad** [comment]
Oh, yeah that's fine. That's been added in e81ca2595087a2fbfcdb8b3d1801ceb5b04d0c5e.
